---
title: "SAP Basin Ranking Shiny App"
author: "J.Hart"
date: "2025-11-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Example: Aggregation and Ranking with dplyr in Shiny
Suppose your dataset is named df with columns region, var1, var2, etc., and the user adjusts input$var1_score, input$var2_score, etc.
```{r}
library(shiny)
library(dplyr)
library(leaflet)

ui <- fluidPage(
  # Inputs for scoring
  numericInput("var1_score", "Var 1 score", value = 1),
  numericInput("var2_score", "Var 2 score", value = 1),
  tableOutput("summary")
)

server <- function(input, output, session) {
  # Example static data frame for illustration
  df <- data.frame(
    region = c("A", "B", "C"),
    var1 = c(5, 3, 1),
    var2 = c(2, 7, 4)
  )

  # Reactive aggregation with dplyr
  scored <- reactive({
    df %>%
      mutate(
        score = var1 * input$var1_score + var2 * input$var2_score
      ) %>%
      arrange(desc(score)) %>%
      mutate(rank = row_number())
  })

  output$summary <- renderTable({
    scored()
  })
}

shinyApp(ui, server)

```
```{r}
numericInput("score_region1", "Region 1 Score", value = 0)
numericInput("score_region2", "Region 2 Score", value = 0)
# Repeat for all regions/variables

```

```{r}
region_scores <- reactive({
  data.frame(region = c("Region 1", "Region 2"),
             score = c(input$score_region1, input$score_region2))
})

ranked_scores <- reactive({
  region_scores() %>% arrange(desc(score))
})

```

```{r}
output$map <- renderLeaflet({
  leaflet() %>%
    addProviderTiles("CartoDB.Positron") %>%
    addPolygons(data = spatial_data,
                fillColor = "grey",
                layerId = ~region)
})

```

```{r}
observe({
  pal <- colorNumeric("YlOrRd", domain = ranked_scores()$score)
  leafletProxy("map") %>%
    clearShapes() %>%
    addPolygons(data = spatial_data,
                fillColor = ~pal(ranked_scores()$score[match(spatial_data$region, ranked_scores()$region)]),
                layerId = ~region)
})

```

```{r}
output$ranking <- renderTable({
  ranked_scores()
})

```

```{r}

```

